---
title: "Workshop Kick Off"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    extra_dependencies: ["float"]
    number_sections: TRUE
    toc: true
    toc_depth: 1
#  html_document:
#    number_sections: TRUE
#    toc: true
#    toc_depth: 1
#    theme: flatly
#    highlight: zenburn
#  word_document:
#    number_sections: TRUE
#    toc: true
#    toc_depth: 1
urlcolor: magenta
geometry: margin=1in
header-includes:
   \usepackage[dvipsnames]{xcolor}
   \usepackage{pifont}
   \usepackage{fontenc}
   \usepackage{anyfontsize}
   \usepackage{inputenc}
---

\vspace{0.75cm}

# Workshop Goal

The PNS documentation (e.g., see \url{https://github.com/jamieyap/PNS}) contains information on study design, how the data collected differed from the intended design, and how such deviations were addressed in the process of constructing the curated datasets. More than a mere collection of facts, the documentation seeks to organize these diverse set of information into a coherent story, allowing end-users of the curated datasets to more quickly...

1. See to what extent is it feasible to investigate a particular scientific question using the data on-hand.
2. See to what extent is it feasible to consider potential advancements in computational methodology.

The workshop seeks to complement the PNS documentation. By the end of this workshop, you will be able to:

* Correctly interpret columns in the curated datasets.
* Correctly identify rows which need to be included/excluded when working on (1) and/or (2) described above.

# Ground Rules

* Questions and lively discussion are encouraged. However, we ask that workshop participants hold off until 'break points' indicated by the following box in your notes. There are no *dumb questions* in this workshop -- we encourage you to raise questions during these break points for the benefit of other workshop participants as well.

\fboxrule.1em\fboxsep1em
\fcolorbox{black}{red!5}{\color{black}
\begin{minipage}[0.30in]{6.3in}
\begin{center}BREAK: Any questions?\end{center}
\end{minipage}}

* Have a pen and paper on hand and get ready to doodle together as we progress through the modules.

* During live demos of R code (Modules 3 and 5), workshop participants are encouraged to use break points to initiate discussion focusing on the logic, rather than syntax, employed in the code.

# What to Expect

**WORKSHOP KICK OFF**

* MODULE 1: Anatomy of `merged.csv`
* MODULE 2: Set-Up of Independent Variables
* MODULE 3: Laying the Groundwork for Set-Up of Dependent Variables through Data Visualization

**\textcolor{Dandelion}{COFFEE/TEA/BAGEL BREAK: 15 minutes}**

* MODULE 4: Set-Up of Dependent Variable
* MODULE 5: Modeling and Hypothesis Testing

**\textcolor{Dandelion}{COFFEE/TEA/BAGEL BREAK: 5 minutes}**

**WORKSHOP WRAP UP**


